data_ingestion:
  url: 'https://docs.google.com/document/d/1ivKxJzrHF79e-p1oQQBGfy3Pa9Yun9Zm/edit?usp=sharing&ouid=109341051897683575625&rtpof=true&sd=true'
  destination_folder: '/home/moraa-ontita/Documents/GenAI/Sales_AI/artifacts/DataIngestion/'
  file_name: 'alkhemy_brands_overview_updated.docx'


global:
  config_path: "./config/config.yaml"

document_loader:
  file_path: "/home/moraa-ontita/Documents/GenAI/Sales_AI/artifacts/DataIngestion/alkhemy_brands_overview_updated.docx"
  save_path: "/home/moraa-ontita/Documents/GenAI/Sales_AI/artifacts/loader/loaded_document.txt"


metadata:
  input_file: "/home/moraa-ontita/Documents/GenAI/Sales_AI/artifacts/loader/loaded_document.txt"  # Use the saved .txt file
  metadata_folder: "/home/moraa-ontita/Documents/GenAI/Sales_AI/artifacts/metadata/"
  document_title: "Alkhemy Brands Overview"
  author: "John Doe"
  document_type: "Overview"
  tags:
    - "sales"
    - "overview"
    - "brands"